### ISSUE TITLE
Where to report bugs or contribute patches?

### ISSUE THREAD

**Issue by guihkx** [flathub/com.dec05eba.gpu_screen_recorder#4]
Hi.

I'm experiencing a random crash right now in `master` ([`5cdb2df3d7433974dbabcf152dede43106ee5b42`](https://git.dec05eba.com/gpu-screen-recorder/commit/?id=5cdb2df3d7433974dbabcf152dede43106ee5b42)), but I couldn't find a place to report a bug, so I'm sorry to report it here.

The crash:

```
$ ./gpu-screen-recorder -w screen -c mp4 -f 60 -q ultra -k h264 -o ~/test.mp4
fish: Job 1, './gpu-screen-recorder -w screen…' terminated by signal SIGSEGV (Address boundary error)
```

gdb backtrace:

```
Thread 1 (Thread 0x7f3cf6375000 (LWP 77311)):
#0  0x00007f3d0624fe11 in av_opt_next () at /usr/lib/libavutil.so.57
#1  0x00007f3d0624ffdc in av_opt_find2 () at /usr/lib/libavutil.so.57
#2  0x00007f3d06256ecd in av_opt_set () at /usr/lib/libavutil.so.57
#3  0x00005602280d382e in open_video (is_livestream=false, video_quality=<optimized out>, use_nvfbc=true, cuda_context=0x5602287ef6d0, cuda_graphics_resource=0x7fff42eae4a0, device_ctx=<synthetic pointer>, window_pixmap=..., codec_context=0x56022919cc00) at src/main.cpp:821
#4  main(int, char**) (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:1462
```

I believe this is fixed by this simple patch:

```diff
diff --git a/src/main.cpp b/src/main.cpp
index 4a634d6..8c5c7aa 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -818,7 +818,7 @@ static void open_video(AVCodecContext *codec_context,
         //av_dict_set(&options, "preset", "llhq", 0);
     }
 
-    av_opt_set(&options, "rc", "vbr", 0);
+    av_dict_set(&options, "rc", "vbr", 0);
 
     ret = avcodec_open2(codec_context, codec_context->codec, &options);
     if (ret < 0) {
```

Is there an official place to report bugs or submit patches?

Thanks.

**Comment by dec05eba** [comment]
Oh hi sorry I didn't get a notification when you made this issue. You can report bugs to my email dec05eba at protonmail dot com. But i'll apply this patch right now, thanks. (stupid mistake :))
